# Generated by Django 6.0.2 on 2026-02-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_compltetasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compltetasks',
            name='status',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dailytasks',
            name='status',
            field=models.CharField(max_length=200),
        ),
    ]
