# Generated by Django 6.0.2 on 2026-02-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_dailytasks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytasks',
            name='status',
            field=models.CharField(choices=[('on progress', 'On progress'), ('completed', 'Completed')], default='on progress', max_length=200),
        ),
    ]
