# Generated by Django 6.0.2 on 2026-02-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_monthlygoals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlygoals',
            name='status',
            field=models.CharField(choices=[('on progress', 'On progress'), ('completed', 'Completed')], default='on progress', max_length=200),
        ),
    ]
